[package]
name = "rust_dream_bot"
version = "0.1.0"
authors = ["Shawn Hulce <shawn_hulce@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.7"
reqwest = "0.9.22"
serde_json = "1.0.41"